-- generated by Digital. Don't modify this file!
-- Any changes will be lost if this file is regenerated.

LIBRARY ieee;
USE ieee.std_logic_1164.all;

entity MUX_GATE_1 is
  port (
    p_out: out std_logic;
    sel: in std_logic;
    
    in_0: in std_logic;
    in_1: in std_logic );
end MUX_GATE_1;

architecture Behavioral of MUX_GATE_1 is
begin
  with sel select
    p_out <=
      in_0 when '0',
      in_1 when '1',
      '0' when others;
end Behavioral;


LIBRARY ieee;
USE ieee.std_logic_1164.all;

entity DIG_D_FF is
   port ( D  : in std_logic;
         C  : in std_logic;
         Q  : out std_logic;
         notQ : out std_logic );
end DIG_D_FF;

architecture Behavioral of DIG_D_FF is
   signal state : std_logic := '0';
begin
   Q    <= state;
   notQ <= NOT( state );

   process(C)
   begin
      if rising_edge(C) then
        state  <= D;
      end if;
   end process;
end Behavioral;


LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity main is
  port (
    SI: in std_logic;
    ShiftDR: in std_logic;
    ClockDR: in std_logic;
    UpdateDR: in std_logic;
    Mode: in std_logic;
    PI1: in std_logic;
    PI0: in std_logic;
    PI2: in std_logic;
    PI3: in std_logic;
    PO0: out std_logic;
    PO1: out std_logic;
    PO2: out std_logic;
    SO: out std_logic;
    PO3: out std_logic);
end main;

architecture Behavioral of main is
  signal s0: std_logic;
  signal s1: std_logic;
  signal s2: std_logic;
  signal s3: std_logic;
  signal s4: std_logic;
  signal s5: std_logic;
  signal s6: std_logic;
  signal s7: std_logic;
  signal s8: std_logic;
  signal SO_temp: std_logic;
  signal s9: std_logic;
  signal s10: std_logic;
begin
  gate0: entity work.MUX_GATE_1
    port map (
      sel => ShiftDR,
      in_0 => PI0,
      in_1 => SI,
      p_out => s0);
  gate1: entity work.DIG_D_FF
    port map (
      D => s0,
      C => ClockDR,
      Q => s2);
  gate2: entity work.DIG_D_FF
    port map (
      D => s2,
      C => UpdateDR,
      Q => s1);
  gate3: entity work.MUX_GATE_1
    port map (
      sel => ShiftDR,
      in_0 => PI1,
      in_1 => s2,
      p_out => s3);
  gate4: entity work.MUX_GATE_1
    port map (
      sel => Mode,
      in_0 => PI0,
      in_1 => s1,
      p_out => PO0);
  gate5: entity work.DIG_D_FF
    port map (
      D => s3,
      C => ClockDR,
      Q => s5);
  gate6: entity work.DIG_D_FF
    port map (
      D => s5,
      C => UpdateDR,
      Q => s4);
  gate7: entity work.MUX_GATE_1
    port map (
      sel => ShiftDR,
      in_0 => PI2,
      in_1 => s5,
      p_out => s6);
  gate8: entity work.MUX_GATE_1
    port map (
      sel => Mode,
      in_0 => PI1,
      in_1 => s4,
      p_out => PO1);
  gate9: entity work.DIG_D_FF
     port map (
      D => s6,
      C => ClockDR,
      Q => s8);
  gate10: entity work.DIG_D_FF
    port map (
      D => s8,
      C => UpdateDR,
      Q => s7);
  gate11: entity work.MUX_GATE_1
    port map (
      sel => ShiftDR,
      in_0 => PI3,
      in_1 => s8,
      p_out => s9);
  gate12: entity work.MUX_GATE_1
    port map (
      sel => Mode,
      in_0 => PI2,
      in_1 => s7,
      p_out => PO2);
  gate13: entity work.DIG_D_FF
    port map (
      D => s9,
      C => ClockDR,
      Q => SO_temp);
  gate14: entity work.DIG_D_FF
    port map (
      D => SO_temp,
      C => UpdateDR,
      Q => s10);
  gate15: entity work.MUX_GATE_1
    port map (
      sel => Mode,
      in_0 => PI3,
      in_1 => s10,
      p_out => PO3);
  SO <= SO_temp;
end Behavioral;
