# Generated by Django 4.1.3 on 2022-12-03 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        ('reader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_return', models.DateField(verbose_name='date of return')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='books.books')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reader.reader')),
            ],
        ),
    ]
