# Network shell
CONFIG_SHELL=y
CONFIG_OPENTHREAD_SHELL=y
CONFIG_SHELL_ARGC_MAX=26
CONFIG_SHELL_CMD_BUFF_SIZE=416

# Enable OpenThread features set
CONFIG_OPENTHREAD_NORDIC_LIBRARY_FTD=y

# L2 enabling
CONFIG_NET_L2_OPENTHREAD=y

# Networking
CONFIG_NETWORKING=y

# OpenThread Joiner
CONFIG_OPENTHREAD_JOINER_AUTOSTART=y
CONFIG_OPENTHREAD_JOINER_PSKD="M3T3R1T"

# EEPROM
CONFIG_EEPROM=y

# I2C
CONFIG_I2C=y

# SPI
CONFIG_SPI=y

CONFIG_MBEDTLS_SHA1_C=n
CONFIG_FPU=y

CONFIG_GPIO_SHELL=y
