#!/bin/bash

# .bcp aaaa
# without any parameter give help and exit
# if ~/backups does not exist try to create it
# if is does not succed exit and inform
# aaaa - link or directory omit, backup only files
# if aaaa is a file copy to ~/backups and add .backup to name
# proceed firstly with one file then with several
#
# program terminates at first argument that cannot be backed up

if [ $# -lt 1 ]
then
	echo "Number of input arguments is too small!"
	echo "You need to select 1 file to be backuped!"
	echo "The input should be: ./bcp file"
	
	exit 0
fi

if [ -d ~/backups ]
then
	echo "Backup directory found"
else
	echo "Backup directory does not exist!"
	echo "Trying to create backup folder"
	
	mkdir ~/backups
	
	if [ -d ~/backups ]
	then
		echo "Backup directory succesfully created"
	else
		echo "Can not create backup directory!"
		
		exit 0
	fi
fi

for i in $@
do
	if [ -e $i ]
		then
			if [ -d $i ]
				then
					echo "File nr '$i' is a directory, it can not be backuped!"
					echo ""
				
					exit 0
				
			elif [ -h $i ]
				then
					echo "File nr '$i' is a symbolic link, it can not be backuped!"
					echo ""
				
					exit 0
			elif [ -f $i ]
				then
					echo "Backing up file '$i' ..."
					echo ""
		
					cp $i ~/backups/$i.backup
			fi
		else
			echo "File nr '$i' does not exist!"
			echo ""
		
			exit 0
	fi
	
	echo "Backup of file '$i' succesfully completed."
	
done

echo ""
